# Generated by Django 3.1.5 on 2021-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100000000000000000000000000000000000000000000000000000000000000000000000000000000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100000000000000000000000000000000000000000000000000000000000000000000000000000000),
        ),
    ]
